fastlane_version '2.58.0'

platform :ios do

  lane :setup_signing do
    setup_travis
    disable_automatic_code_signing(path: "ios/Mortars.xcodeproj")
    match(app_identifier: 'xyz.padarom.mortars', type: 'appstore')
  end

  lane :update_signing do
    match(type: 'appstore')
  end

  lane :set_new_build_number do
    build_number = Time.new.strftime('%Y%m%d%H%M')
    increment_build_number(build_number: build_number, xcodeproj: './ios/Mortars.xcodeproj')
  end

  lane :deploy do
    setup_signing
    set_new_build_number
    ship
  end

  lane :ship do
    gym(
      workspace: './ios/Mortars.xcworkspace',
      configuration: 'Release',
      scheme: 'Mortars',
      export_options: {
        provisioningProfiles: {
          "xyz.padarom.mortars": "match AppStore xyz.padarom.mortars"
        }
      }
    )
    pilot(username: ENV['FASTLANE_USERNAME'], skip_waiting_for_build_processing: true)

    version_number = get_version_number(xcodeproj: './ios/Mortars.xcodeproj')
    build_number = get_build_number(xcodeproj: './ios/Mortars.xcodeproj')

    tag = "deploy-#{version_number}-#{build_number}"
    add_git_tag(tag: tag)

    sh('git', 'remote', 'add', 'http', "https://#{ENV['GITHUB_TOKEN']}@github.com/padarom/mortars.git")
    push_git_tags(remote: 'http')
  end

end
